void mainLoop ();
void run ();
int main ();
void keyCallback (GLFWwindow* window, int key, int scancode, int action, int mods);
void errorCallback (int err, const char* description);
static void framebufferResizeCallback (GLFWwindow* window, int width, int height);
void initWindow ();
void cleanupWindow ();
void uploadTex (const void* image, int w, int h);
void initDraw ();
void cleanupDraw ();
void drawFrame ();
void initGui ();
void cleanupGui ();
void drawGui ();
void createContext ();
void createModule ();
void createRayGenPrograms ();
void createExceptionPrograms ();
void createMissPrograms ();
void createHitGroupPrograms ();
void createPipeline ();
void buildSBT ();
void render ();
void resize (int x, int y);
void download_pixels (uint32_t* h_pixels);
void set_camera (const camera_t& camera);
OptixTraversableHandle buildAccel (const triangle_mesh_t& model);
void initOptix (const triangle_mesh_t& model);
void cleanupOptix ();
